tz_user:
  resource: "@UserBundle/Resource/config/routing/user.yml"
  prefix:   /admin/user

tz_login:
  path: /login
  defaults: { _controller: UserBundle:Security:login }

tz_resetting_password:
  path: /{_locale}/resetting-password
  defaults: { _controller: "UserBundle:User:resettingPassword", _locale : fr }
  methods: [GET, POST]
  requirements:
    _locale: en|fr