services:
  tz.manager.user:
    class: App\Sekoliko\Service\UserBundle\Manager\UserManager
    arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
    public: true

  tz.handler.login_success_handler:
    class:  App\Sekoliko\Service\UserBundle\Manager\AfterLoginRedirection
    arguments:  ['@router', '@security.authorization_checker', '@service_container']